dist: xenial
language: minimal
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - build-essential
      - cmake
      - clang-7
      - g++-7
      - libc++-7-dev
      - libc++abi-7-dev
      - ninja-build
      - lcov
env:
  - GRAPH_SIZE=725 BUILD_TYPE=Release LDFLAGS="-stdlib=libc++" CC="clang-7" CXX="clang++-7" CXXFLAGS="-std=c++17 -stdlib=libc++ -D_LIBCPP_VERSION=1"
  - GRAPH_SIZE=50  BUILD_TYPE=Debug   LDFLAGS="-stdlib=libc++" CC="clang-7" CXX="clang++-7" CXXFLAGS="-std=c++17 -stdlib=libc++ -D_LIBCPP_VERSION=1 -fno-omit-frame-pointer -fsanitize=address"
  - GRAPH_SIZE=50  BUILD_TYPE=Release LDFLAGS="-stdlib=libc++" CC="clang-7" CXX="clang++-7" CXXFLAGS="-std=c++17 -stdlib=libc++ -D_LIBCPP_VERSION=1 -fno-omit-frame-pointer -fsanitize=address"
  - GRAPH_SIZE=725 BUILD_TYPE=Release                          CC="gcc-7"   CXX="g++-7"     CXXFLAGS="-std=c++17"
  - GRAPH_SIZE=50  BUILD_TYPE=Debug                            CC="gcc-7"   CXX="g++-7"     CXXFLAGS="-std=c++17 -fno-omit-frame-pointer -fsanitize=address"
script:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGRAPH_SIZE=$GRAPH_SIZE ..
  - ninja
  - ./cpp-serialization-benchmark --benchmark_min_time=0.0001
  - ./cista-compile-time
  - ./capnp-compile-time
# - ./fbs-compile-time
  - ./cereal-compile-time
